variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}
variable "instance_type" {
  description = "Lightsail bundle ID"
  type        = string
  default     = "nano_3_0"
}
variable "availability_zone_suffix" {
  description = "Availability zone suffix"
  type        = string
  default     = "a"
}
variable "ssh_key_pair_name" {
  description = "Optional existing Lightsail key pair name"
  type        = string
  default     = null
  nullable    = true
}
variable "ssh_allowed_cidr" {
  description = "IPv4 CIDR allowed to connect over SSH"
  type        = string
  default     = "127.0.0.1/32"
}
variable "wireguard_port" {
  description = "WireGuard UDP port"
  type        = number
  default     = 51820
  validation {
    condition     = var.wireguard_port >= 1 && var.wireguard_port <= 65535
    error_message = "wireguard_port must be from 1 through 65535."
  }
}
variable "server_private_key" {
  description = "WireGuard server private key generated by the application"
  type        = string
  sensitive   = true
}
variable "server_public_key" {
  description = "WireGuard server public key"
  type        = string
}
variable "client_peers" {
  description = "WireGuard client peers containing public keys and unique tunnel IPv4 addresses"
  type = list(object({
    id          = string
    public_key  = string
    tunnel_ipv4 = string
  }))
  default = []
  validation {
    condition     = length(var.client_peers) <= 10 && alltrue([for peer in var.client_peers : length(peer.public_key) > 0 && can(cidrhost("${peer.tunnel_ipv4}/32", 0))])
    error_message = "client_peers must contain at most 10 valid public-key/tunnel-address entries."
  }
}
variable "client_public_key" {
  description = "Legacy single-client public key retained for recovery compatibility"
  type        = string
  default     = null
  nullable    = true
}
variable "user_data_payload" {
  description = "Validated provider-safe bootstrap payload generated by the application"
  type        = string
  default     = null
  nullable    = true
  sensitive   = true
}
variable "deployment_id" {
  description = "Application deployment UUID used for ownership and unique names"
  type        = string
  default     = "manual"
}
variable "expires_at" {
  description = "Best-effort local expiration timestamp; no cloud-side reaper is implied"
  type        = string
  default     = null
  nullable    = true
}
variable "ssh_public_key" {
  description = "Per-deployment OpenSSH public key imported by the application"
  type        = string
  default     = null
  nullable    = true
}
