variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}
variable "instance_type" {
  description = "Lightsail bundle ID"
  type        = string
  default     = "nano_3_0"
}
variable "availability_zone_suffix" {
  description = "Availability zone suffix"
  type        = string
  default     = "a"
}
variable "ssh_key_pair_name" {
  description = "Optional existing Lightsail key pair name"
  type        = string
  default     = null
  nullable    = true
}
variable "ssh_allowed_cidr" {
  description = "IPv4 CIDR allowed to connect over SSH"
  type        = string
  default     = "127.0.0.1/32"
}
variable "wireguard_port" {
  description = "WireGuard UDP port"
  type        = number
  default     = 51820
  validation {
    condition     = var.wireguard_port >= 1 && var.wireguard_port <= 65535
    error_message = "wireguard_port must be from 1 through 65535."
  }
}
variable "server_private_key" {
  description = "WireGuard server private key generated by the application"
  type        = string
  sensitive   = true
}
variable "server_public_key" {
  description = "WireGuard server public key"
  type        = string
}
variable "client_public_key" {
  description = "WireGuard client public key"
  type        = string
}
