const STATES = ['validating_credentials','initializing','planning','provisioning','waiting_for_cloud_init','checking_wireguard','verifying_egress','ready'];
const $ = (id) => document.getElementById(id);
let providers = [], locations = [], deploymentId = null, operationId = null, startedAt = null, timer = null;
const api = () => window.pywebview?.api;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function selectedProvider(){ return providers.find((p) => p.id === $('provider').value); }
function selectedLocation(){ return locations.find((l) => l.id === $('location').value); }
function option(el, value, label){ const node=document.createElement('option'); node.value=value; node.textContent=label; el.append(node); }
function setBusy(busy){ $('deploy').disabled=busy; $('cancel').disabled=!busy || !deploymentId; $('provider').disabled=busy; $('country').disabled=busy; $('location').disabled=busy; }
function stateLabel(value){ return value.replaceAll('_',' ').replace(/^./,(c)=>c.toUpperCase()); }
function renderSteps(state){ $('steps').replaceChildren(...STATES.map((value)=>{ const li=document.createElement('li'); li.textContent=stateLabel(value); const index=STATES.indexOf(state); li.className=STATES.indexOf(value)<index?'done':value===state?'active':''; return li; })); }
function setState(record){ if(!record)return; deploymentId=record.id || deploymentId; const state=record.state || 'idle'; $('status-text').textContent=stateLabel(state); $('status-dot').className=`status-indicator ${state}`; $('ip-address').textContent=record.public_ip || '—'; $('copy-ip').disabled=!record.public_ip; $('expires').textContent=record.expires_at ? new Date(record.expires_at).toLocaleString() : '—'; $('destroy').disabled=!deploymentId || state==='destroyed'||state==='destroying'; renderSteps(state); }
function refreshLocations(){ const provider=selectedProvider(); locations=provider?.locations||[]; const countries=[...new Map(locations.map((l)=>[l.country_code,l.country_name])).entries()]; $('country').replaceChildren(); countries.forEach(([id,name])=>option($('country'),id,name)); refreshRegions(); }
function refreshRegions(){ const country=$('country').value; const values=locations.filter((l)=>l.country_code===country); $('location').replaceChildren(); values.forEach((l)=>option($('location'),l.id,`${l.city} — ${l.region}`)); refreshBadges(); }
function refreshBadges(){ const location=selectedLocation(); if(!location)return; $('server-type').textContent=location.server_type; $('streaming').textContent=location.streaming_status; $('cost').textContent=location.estimated_hourly_cost_usd==null?'Cost unavailable':`~$${location.estimated_hourly_cost_usd.toFixed(3)}/hour`; }
function deploymentOptions(){ return {allowed_ips:$('allowed-ips').value.split(',').map(v=>v.trim()).filter(Boolean),enable_ipv6:false,dns_servers:$('dns').value.split(',').map(v=>v.trim()).filter(Boolean),wireguard_port:Number($('port').value),client_mtu:Number($('mtu').value),persistent_keepalive:Number($('keepalive').value),ssh_cidr:$('ssh-cidr').value.trim(),expiration_minutes:$('expiration').value?Number($('expiration').value):null,automatic_expiration:Boolean($('expiration').value)}; }
async function deploy(){ setBusy(true); startedAt=Date.now(); startTimer(); const response=await api().start_deploy($('provider').value,$('location').value,deploymentOptions()); operationId=response.operation_id; while(true){ const status=await api().operation_status(operationId); if(status.deployment){setState(status.deployment); await refreshLogs();} if(status.status==='complete'){ const result=status.result; deploymentId=result.deployment_id; setState({id:deploymentId,state:result.state,public_ip:result.ip,expires_at:result.expires_at}); if(result.status!=='success')throw new Error(result.message); await showConfig(result.config); break;} await sleep(500);} setBusy(false); }
async function refreshLogs(){ if(!deploymentId)return; const lines=await api().get_logs(deploymentId); $('logs').textContent=lines.join('\n'); $('logs').scrollTop=$('logs').scrollHeight; }
async function showConfig(config){ const node=$('qrcode'); $('qr-row').classList.remove('hidden'); node.replaceChildren(); if(window.QRCode){new QRCode(node,{text:config,width:152,height:152,correctLevel:QRCode.CorrectLevel.M});}else{node.textContent='QR library unavailable. Save the configuration instead.';} }
async function destroy(){ if(!deploymentId||!confirm('Destroy this deployment and delete its local client configuration?'))return; setBusy(true); const result=await api().destroy(deploymentId,false); if(result.status!=='success')alert(result.message); else {setState({id:deploymentId,state:'destroyed'}); $('qr-row').classList.add('hidden');} setBusy(false); await loadRecovery(); }
async function loadRecovery(){ const items=await api().list_recovery_deployments(); $('recovery').classList.toggle('hidden',!items.length); $('recovery-list').replaceChildren(...items.map((item)=>{const button=document.createElement('button');button.className='recovery-item';button.textContent=`${item.provider_id} / ${item.location_id} — ${stateLabel(item.state)}`;button.onclick=()=>{deploymentId=item.id;setState(item);};return button;})); }
function startTimer(){ clearInterval(timer); timer=setInterval(()=>{if(startedAt){const seconds=Math.floor((Date.now()-startedAt)/1000);$('elapsed').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}},1000); }
async function initialize(){ if(!api()){setTimeout(initialize,100);return;} providers=await api().list_providers(); $('provider').replaceChildren(); providers.forEach((p)=>option($('provider'),p.id,p.display_name)); refreshLocations(); renderSteps('idle'); await loadRecovery(); }
$('provider').addEventListener('change',refreshLocations); $('country').addEventListener('change',refreshRegions); $('location').addEventListener('change',refreshBadges); $('traffic-mode').addEventListener('change',()=>{$('allowed-ips').disabled=$('traffic-mode').value!=='custom';});
$('deploy').addEventListener('click',()=>deploy().catch((e)=>{alert(e.message);setBusy(false);})); $('destroy').addEventListener('click',destroy); $('cancel').addEventListener('click',async()=>{if(deploymentId)await api().cancel(deploymentId);});
$('copy-ip').addEventListener('click',()=>navigator.clipboard.writeText($('ip-address').textContent)); $('save-config').addEventListener('click',async()=>{const destination=prompt('Save to an absolute path (for example C:\\Users\\you\\WireGuard\\vpn.conf):');if(destination)await api().save_client_config(deploymentId,destination);});
window.addEventListener('beforeunload',(event)=>{if(deploymentId&&$('status-text').textContent!=='Destroyed'){event.preventDefault();event.returnValue='Active cloud resources may still exist.';}}); document.addEventListener('DOMContentLoaded',initialize);
